
ALTER TABLE PLAN_TIENDA ADD D_DATE_CREATE DATETIME
ALTER TABLE PLAN_TIENDA DROP COLUMN D_FECHA_CREATE 

DROP TABLE PLAN_TIENDA;
DROP TABLE PLANES;

CREATE TABLE PLANES
(
I_PLAN INT IDENTITY(1,1) PRIMARY KEY,
MONTO_PLAN DECIMAL(10,2),
NOMBRE NVARCHAR(50),
DESCRIPCION VARCHAR(1000),
ESTADO CHAR(1)
);

CREATE TABLE PLAN_TIENDA
(
I_PLANTIENDA INT IDENTITY(1,1) PRIMARY KEY,
I_PLAN INT FOREIGN KEY REFERENCES PLANES(I_PLAN), -- ID DEL PLAN (0: VERSION FREE)
I_TIPO CHAR(1),--M MENSUAL, A ANUAL.
I_CODIGO_TIENDA INT FOREIGN KEY REFERENCES TIENDA(I_CODIGO_TIENDA),
MONTO_PLAN DECIMAL(10,2),
PERIODOINI_FAC DATE,-- FECHA DE INICIO Y FIN DEL PLAN
PERIODOFIN_FAC DATE,
IMPORTE DECIMAL(10,2),
ESTADO CHAR(1),--1 ACTIVO, 0 INACTIVO
FECHA_PAGO DATETIME,-- FECHA DE PAGO
V_USER_CREATE NVARCHAR(100),
D_DATE_CREATE DATETIME,
D_DATE_UPDATE DATETIME,
V_USER_UPDATE NVARCHAR(100)
);