
/*
DELETE FROM dbo.PRODUCTO WHERE I_CODIGO_TIENDA = 4
DELETE FROM dbo.IMAGEN_PRODUCTO WHERE I_CODIGO_PRODUCTO IN (SELECT I_CODIGO_PRODUCTO FROM dbo.PRODUCTO WHERE I_CODIGO_TIENDA = 4)
DELETE FROM dbo.PRODUCTO_CARACTERISTICA WHERE I_CODIGO_PRODUCTO IN (SELECT I_CODIGO_PRODUCTO FROM dbo.PRODUCTO WHERE I_CODIGO_TIENDA = 4)
DELETE FROM dbo.DETALLE_COMPRA WHERE I_CODIGO_PRODUCTO IN (SELECT I_CODIGO_PRODUCTO FROM dbo.PRODUCTO WHERE I_CODIGO_TIENDA = 4)
*/

SELECT * FROM USUARIO
SELECT * FROM [dbo].[CATEGORIA];
SELECT * FROM [dbo].[TIENDA]
SELECT * FROM dbo.PRODUCTO
SELECT * FROM dbo.CARRITO_COMPRA

/*
 ---------------- MATRICULAMOS LA TIENDA --------------
UPDATE dbo.TIENDA SET 
V_TIENDA = 'RICHARDVIGNARTCHILE',
 V_RAZON_SOCIAL = 'RICHARD VIGNART CHILE',
 V_DESCRIPCION = 'CAFÉ Y CHOCOLATES ORO NEGRO DE QUILLABAMBA',
 V_DIRECCION = 'MERCADO SAN PEDRO SECCIÓN CHOCOLATES INTERIOR N# 592',
 V_WEB = 'https://preview.oklerthemes.com/porto/8.0.0/demo-coffee.html'
  WHERE I_CODIGO_TIENDA = 1;

---------------- MATRICULAMOS EL DUENO DE LA TIENDA --------------
  UPDATE dbo.USUARIO SET 
	I_TIENDA = '4'
  WHERE IDUSUARIO = 1;

 */
--ALTER TABLE dbo.[TIENDA] ADD V_DESCRIPCION NVARCHAR(1000)
--ALTER TABLE PRODUCTO DROP COLUMN DESCRIPCION
--ALTER TABLE dbo.PRODUCTO ADD V_DESCRIPCION NVARCHAR(500)
--ALTER TABLE dbo.PRODUCTO ALTER COLUMN V_PRODUCTO NVARCHAR(250)
--DELETE FROM dbo.CATEGORIA 



